name: 'Terragrunt Build and Test'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - run: cd aws/gitlab/test && go mod init aws_gitlab_test.go; go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.54
        working-directory: aws/gitlab/test
        skip-pkg-cache: true
